services:
  nexus-command:
    image: eclipse-temurin:17-jdk
    working_dir: /app
    command: ./mvnw install -DskipTests && ./mvnw -pl webapp spring-boot:run
    ports:
      - "8080:8080"
    environment:
      - LOGGING_LEVEL_ROOT=WARN
      - ECLIPSELINK_LOGGING_LEVEL=WARNING
      - JDBC_LOGGING=false
      - nexus.modules.organizations.enabled=true
      - nexus.modules.projects.enabled=true
      - nexus.modules.franchise.enabled=true
      - nexus.modules.web.enabled=true
      - nexus.modules.org-web.enabled=true
      - nexus.modules.security.enabled=true
      - nexus.modules.products.enabled=true
      - nexus.modules.webhooks.enabled=true
      - nexus.modules.kafka.enabled=true
      - nexus.security.enabled=false
      - nexus.seed.enabled=true
      - nexus.seed.admin.enabled=true
      - nexus.seed.admin.username=admin
      - nexus.seed.admin.password=admin
    volumes:
      - .:/app
      - m2:/root/.m2

  kafka:
    image: confluentinc/confluent-local:7.4.1
    hostname: kafka
    container_name: kafka
    ports:
      - "8082:8082"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9999:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

volumes:
    m2: {}