#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#

nexus:
  security:
    debug: true # debug web security
    oauth2:
      enabled: false # use this to enable general oauth2 security
      roles:
        sticky:
        - application-user # default roles for all users
        claim: $.roles # the jwt claim to get the roles from
        mappings: # map oauth2 roles to application roles
          admin: causeway-ext-secman-admin
          user: application-user
      login: 
        enabled: false # use this to enable the oauth2 login page
        name: "oauth2"
        client-id: "nexus"
        client-secret: "nexus"
        scope: "openid profile email roles"
        username-attribute: "preferred_username"
        issuer-uri: "http://localhost:8080/auth/realms/nexus"
        authorization-uri: "http://localhost:8080/auth/realms/nexus/protocol/openid-connect/auth"
        token-uri: "http://localhost:8080/auth/realms/nexus/protocol/openid-connect/token"
        user-info-uri: "http://localhost:8080/auth/realms/nexus/protocol/openid-connect/userinfo"
        jwk-set-uri: "http://localhost:8080/auth/realms/nexus/protocol/openid-connect/certs"
        registration-id: "oauth2"
  products:
    enabled: true
  organizations:
    enabled: true
  projects:
    enabled: true
  flow:
    enabled: true
  franchise:
    enabled: true
  org-fees:
    enabled: true
  audited-entity:
    enabled: true
  ai:
    enabled: true
  agents:
    enabled: true
  kafka:
    enabled: true
  webhooks:
    enabled: true
  web:
    enabled: false
  org-web:
    enabled: false
  google:
    analytics:
      enabled: true
      flow:
        enabled: true
  encryption:
    secret: "12312312312312312312312312312312" # don't use this secret in production

  

causeway:
  applib:
    annotation:
      action:
        explicit: true
        command-publishing: all
        execution-publishing: all
      #action-layout:
      #  css-class:
      #    patterns:
      #      delete.*:btn-danger,
      #      discard.*:btn-warning,
      #      remove.*:btn-warning
      property:
        command-publishing: all
        execution-publishing: all
      domain-object:
        editing: false
        entity-change-publishing: all
  core:
    meta-model:
      introspector:
        lock-after-full-introspection: true
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true
    runtime-services:
      email:
        sender:
          address: ${spring.mail.from}
      translation:
        po:
          mode: disabled
  persistence:
    schema:
      auto-create-schemas:
      - public
      - agents
      - products
      - projects
      - flow
      - nc_web
      - organizations
      - orgweb
      - franchise
      - webhooks
      - kafka
      - google_analytics
      - google_analytics_flow
      - causewayExtSecman
      - causewayExtAuditTrail
      - causewayExtCommandLog
      - causewayExtExecutionLog
      - causewayExtExecutionOutbox
      - causewayExtSessionLog
  extensions:
    secman:
      seed:
        admin:
          user-name: "secman-admin"
          password: "pass"
          role-name: "causeway-ext-secman-admin"
          namespace-permissions:
            sticky: 
            - public  
#            additional: ...
        regular-user:
          role-name: "causeway-ext-secman-user"
          namespace-permissions:
            sticky:
            - public
      user-registration:
        initial-roles:
          - application-user
          - causeway-ext-secman-user
      permissions-evaluation-policy: allow_beats_veto
      user-menu-me-action-policy: hide
  viewer:
    common:
      application:
        about: Nexus Command
        brand-logo-signin: images/favicon.png
        brand-logo-header: images/favicon.png
        favicon-url: images/favicon.png
        menubars-layout-file: menubars.layout.xml
        name: Nexus Command
        # https://stackoverflow.com/a/38983935/56880
        version: @project.version@
      credit:
        - url:  https://savantly.net
          image: images/favicon.png
          name: Savantly LLC
    wicket:
      css: css/application.css
      js: scripts/application.js
      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true
      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0
      themes:
        show-chooser: true
      table:
        decoration:
          data-tables-net:
            options: "info: false, pagingType: 'numbers'"
  testing:
    fixtures:
      fixture-scripts-specification:
        context-class: domainapp.webapp.application.fixture.scenarios.DemoFixtures
        run-script-default: domainapp.webapp.application.fixture.scenarios.DemoFixtures
#        recreate: domainapp.webapp.application.fixture.scenarios.DemoFixtures
#        non-persisted-objects-strategy: persist
#        multiple-execution-strategy: execute

eclipselink:
  # if enabled, then must be run with JVM arg:
  # -javaagent:lib/spring-instrument-5.3.8.jar
  weaving: false
  # if weaving subproperties are required, then specify all eclipselink.weaving
  # properties using application.properties instead (it's not possible to
  # specify both eclipselink.weaving property and its subproperties using yaml syntax)


resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  max-http-header-size: 16KB
  port: ${PORT:8080}

spring:
  banner:
    location: banner.txt
  quartz:
    job-store-type: memory
  mail:
    host: localhost
    port: 25
    username: user
    password: password
    from: user@localhost
    javamail.properties.mail.smtp.starttls.enable: false
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false

management:
  endpoint:
    health:
      enabled: true
